# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OhhAuth'

  # Pods for TwitterFeed

  target 'TwitterFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'TwitterFeedIntegrationTests' do
      project 'TwitterFeed'
      use_frameworks! # Required for Swift Test Targets only
      inherit! :search_paths # Required for not double-linking libraries in the app and test targets.
      pod 'EarlGrey'
  end

end
